USE [HIVIMAR_EBIZ]
GO

/****** Object:  StoredProcedure [dbo].[STP_ABC]    Script Date: 28/3/2022 10:46:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


















ALTER PROCEDURE [dbo].[STP_ABC] 
AS
--DROP TABLE #TABLA_STOCK_ABC_LOGICA_1

--DROP TABLE #TABLA_STOCK_ABC_LOGICA_2

SELECT B.MARCA,A.COD_MATERIAL,B.TEXT_STATUS AS ESTADO_MATERIAL, SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_BLOQUEADO + ECS_CALIDAD) AS STOCK_DOLARES
into #TABLA_STOCK_ABC_LOGICA_1
FROM EBIZ_STOCK_AL_CIERRE A
LEFT JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE origen = 'hana'
AND YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))
GROUP BY B.MARCA,A.COD_MATERIAL,B.TEXT_STATUS

SELECT B.marca, SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_BLOQUEADO + ECS_CALIDAD) AS STOCK_DOLARES
into #TABLA_STOCK_ABC_LOGICA_2
FROM EBIZ_STOCK_AL_CIERRE A
INNER JOIN EBIZ_MATERIALES B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE ORIGEN = 'hana'
and  YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))
GROUP BY B.marca





--DROP TABLE #TABLA_COSTO_ABC_VENTAS

SELECT A.COD_MATERIAL AS COD_MATERIAL, COSTO_INTERNO as costo_interno
INTO #TABLA_COSTO_ABC_VENTAS
FROM ebiz_ventas A
--INNER JOIN ebiz_materiales B ON A.COD_MATERIAL_CUSTOM = B.COD_MATERIAL_CUSTOM
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-24,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')


--DROP TABLE #TABLA_COSTO_ABC_VENTAS_2

SELECT A.*, B.marca
into #TABLA_COSTO_ABC_VENTAS_2
FROM #TABLA_COSTO_ABC_VENTAS A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE  A.COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_articulo like '%Ing.&Egr.Financieros%' or grupo_articulo like 'Servicio Logistico%') )



--DROP TABLE #TABLA_COSTO_ABC_LOGICA_1

SELECT marca,COD_MATERIAL, SUM(COSTO_INTERNO) AS COSTO_INTERNO
INTO #TABLA_COSTO_ABC_LOGICA_1
FROM #TABLA_COSTO_ABC_VENTAS_2 
GROUP BY  marca,COD_MATERIAL

--DROP TABLE #TABLA_COSTO_ABC_LOGICA_2

SELECT marca, SUM(COSTO_INTERNO) AS COSTO_INTERNO
INTO #TABLA_COSTO_ABC_LOGICA_2
FROM #TABLA_COSTO_ABC_VENTAS_2 
GROUP BY  marca


DELETE FROM EBIZ_ABC_COSTO_INTERNO WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

DELETE FROM EBIZ_ABC_STOCK WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

INSERT INTO EBIZ_ABC_COSTO_INTERNO
SELECT TBCOSTO.marca, TBCOSTO.COD_MATERIAL, TBCOSTO.PESO, TBCOSTO.PESO_ACUMULADO,
CASE WHEN TBCOSTO.PESO_ACUMULADO >= 0 AND TBCOSTO.PESO_ACUMULADO <= 0.8 THEN 'A'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.8 AND TBCOSTO.PESO_ACUMULADO <= 0.95 THEN 'B'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.95 AND TBCOSTO.PESO_ACUMULADO <= 1 THEN 'C'
	  ELSE 'C' END AS ABC_COSTO_VALUE,
	  (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))  AS FECHA_CIERRE
--INTO 
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.MARCA, TB1.COSTO_INTERNO DESC) AS PESO_ACUMULADO
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.COSTO_INTERNO, TB2.COSTO_INTERNO AS COSTO_INTERNO_MARCA, 
CASE WHEN TB2.COSTO_INTERNO = NULL THEN 0
 WHEN TB2.COSTO_INTERNO = 0 THEN 0
ELSE (CAST(TB1.COSTO_INTERNO AS decimal(18,10)) / CAST(TB2.COSTO_INTERNO AS decimal(18,10)) ) END AS PESO 

FROM #TABLA_COSTO_ABC_LOGICA_1 TB1


INNER JOIN #TABLA_COSTO_ABC_LOGICA_2 TB2 ON TB1.marca = TB2.marca ) TB1 ) TBCOSTO




INSERT INTO EBIZ_ABC_STOCK
SELECT TBSTOCK.marca, TBSTOCK.COD_MATERIAL, TBSTOCK.PESO, TBSTOCK.PESO_ACUMULADO,TBSTOCK.ESTADO_MATERIAL,
CASE WHEN TBSTOCK.PESO_ACUMULADO >= 0 AND TBSTOCK.PESO_ACUMULADO <= 0.8 THEN 'A'
	  WHEN TBSTOCK.PESO_ACUMULADO > 0.8 AND TBSTOCK.PESO_ACUMULADO <= 0.95 THEN 'B'
	  WHEN TBSTOCK.PESO_ACUMULADO > 0.95 AND TBSTOCK.PESO_ACUMULADO <= 1 THEN 'C'
	  ELSE 'C' END AS ABC_STOCK_VALUE,
	   (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))   AS FECHA_CIERRE
	--  INTO EBIZ_ABC_STOCK
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,TB1.ESTADO_MATERIAL,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.MARCA, TB1.STOCK_DOLARES DESC) AS PESO_ACUMULADO
FROM (

SELECT TB1.marca, TB1.COD_MATERIAL,TB1.ESTADO_MATERIAL, TB1.STOCK_DOLARES, TB2.STOCK_DOLARES AS STOCK_MARCA, 
CASE WHEN TB2.STOCK_DOLARES = NULL THEN 0
 WHEN TB2.STOCK_DOLARES = 0 THEN 0
ELSE (CAST(TB1.STOCK_DOLARES AS decimal(18,10)) / CAST(TB2.STOCK_DOLARES AS decimal(18,10)) ) END AS PESO 
FROM #TABLA_STOCK_ABC_LOGICA_1 TB1 

LEFT JOIN #TABLA_STOCK_ABC_LOGICA_2 TB2 ON TB1.marca =TB2.marca ) TB1 ) TBSTOCK	


INSERT INTO EBIZ_ABC_COSTO_INTERNO
SELECT DISTINCT MARCA,COD_MATERIAL,0,0,'C',(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
FROM ebiz_materiales 
where cod_material not in (
SELECT DISTINCT COD_MATERIAL
FROM EBIZ_ABC_COSTO_INTERNO 
WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) ) 
and origen = 'hana'

INSERT INTO EBIZ_ABC_STOCK
SELECT DISTINCT MARCA,COD_MATERIAL,0,0,TEXT_STATUS,'C',(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
FROM ebiz_materiales 
where cod_material not in (
SELECT DISTINCT COD_MATERIAL
FROM EBIZ_ABC_STOCK 
WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) ) 
and origen = 'hana'






DROP TABLE #TABLA_STOCK_ABC_LOGICA_1

DROP TABLE #TABLA_STOCK_ABC_LOGICA_2

DROP TABLE #TABLA_COSTO_ABC_VENTAS

DROP TABLE #TABLA_COSTO_ABC_VENTAS_2

DROP TABLE #TABLA_COSTO_ABC_LOGICA_1

DROP TABLE #TABLA_COSTO_ABC_LOGICA_2

----------------------------------- AC 12 & 36 MESES -------------------------------------------------

------------------------------------ 12 MESES --------------------------------------



SELECT B.MARCA,A.COD_MATERIAL,B.TEXT_STATUS AS ESTADO_MATERIAL, SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_BLOQUEADO + ECS_CALIDAD) AS STOCK_DOLARES
into #TABLA_STOCK_ABC_LOGICA_1_12MESES
FROM EBIZ_STOCK_AL_CIERRE A
LEFT JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE origen = 'hana'
AND YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))
GROUP BY B.MARCA,A.COD_MATERIAL,B.TEXT_STATUS

SELECT B.marca, SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_BLOQUEADO + ECS_CALIDAD) AS STOCK_DOLARES
into #TABLA_STOCK_ABC_LOGICA_2_12MESES
FROM EBIZ_STOCK_AL_CIERRE A
INNER JOIN EBIZ_MATERIALES B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE ORIGEN = 'hana'
and  YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))
GROUP BY B.marca

------------------------------------ 12 MESES --------------------------------------

--DROP TABLE #TABLA_COSTO_ABC_VENTAS

SELECT A.COD_MATERIAL AS COD_MATERIAL, COSTO_INTERNO as costo_interno
INTO #TABLA_COSTO_ABC_VENTAS_12MESES
FROM ebiz_ventas A
--INNER JOIN ebiz_materiales B ON A.COD_MATERIAL_CUSTOM = B.COD_MATERIAL_CUSTOM
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')


--DROP TABLE #TABLA_COSTO_ABC_VENTAS_2

SELECT A.*, B.marca
into #TABLA_COSTO_ABC_VENTAS_2_12MESES
FROM #TABLA_COSTO_ABC_VENTAS_12MESES A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE  A.COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_articulo like '%Ing.&Egr.Financieros%' or grupo_articulo like 'Servicio Logistico%') )



--DROP TABLE #TABLA_COSTO_ABC_LOGICA_1

SELECT marca,COD_MATERIAL, SUM(COSTO_INTERNO) AS COSTO_INTERNO
INTO #TABLA_COSTO_ABC_LOGICA_1_12MESES
FROM #TABLA_COSTO_ABC_VENTAS_2_12MESES
GROUP BY  marca,COD_MATERIAL

--DROP TABLE #TABLA_COSTO_ABC_LOGICA_2

SELECT marca, SUM(COSTO_INTERNO) AS COSTO_INTERNO
INTO #TABLA_COSTO_ABC_LOGICA_2_12MESES
FROM #TABLA_COSTO_ABC_VENTAS_2_12MESES
GROUP BY  marca

DELETE FROM EBIZ_ABC_COSTO_INTERNO_12MESES WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

DELETE FROM EBIZ_ABC_STOCK_12MESES WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

INSERT INTO EBIZ_ABC_COSTO_INTERNO_12MESES
SELECT TBCOSTO.marca, TBCOSTO.COD_MATERIAL, TBCOSTO.PESO, TBCOSTO.PESO_ACUMULADO,
CASE WHEN TBCOSTO.PESO_ACUMULADO >= 0 AND TBCOSTO.PESO_ACUMULADO <= 0.8 THEN 'A'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.8 AND TBCOSTO.PESO_ACUMULADO <= 0.95 THEN 'B'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.95 AND TBCOSTO.PESO_ACUMULADO <= 1 THEN 'C'
	  ELSE 'C' END AS ABC_COSTO_VALUE,
	  (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))  AS FECHA_CIERRE
--INTO 
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.MARCA, TB1.COSTO_INTERNO DESC) AS PESO_ACUMULADO
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.COSTO_INTERNO, TB2.COSTO_INTERNO AS COSTO_INTERNO_MARCA, 
CASE WHEN TB2.COSTO_INTERNO = NULL THEN 0
 WHEN TB2.COSTO_INTERNO = 0 THEN 0
ELSE (CAST(TB1.COSTO_INTERNO AS decimal(18,10)) / CAST(TB2.COSTO_INTERNO AS decimal(18,10)) ) END AS PESO 

FROM #TABLA_COSTO_ABC_LOGICA_1_12MESES TB1


INNER JOIN #TABLA_COSTO_ABC_LOGICA_2_12MESES TB2 ON TB1.marca = TB2.marca ) TB1 ) TBCOSTO


INSERT INTO EBIZ_ABC_STOCK_12MESES
SELECT TBSTOCK.marca, TBSTOCK.COD_MATERIAL, TBSTOCK.PESO, TBSTOCK.PESO_ACUMULADO,TBSTOCK.ESTADO_MATERIAL,
CASE WHEN TBSTOCK.PESO_ACUMULADO >= 0 AND TBSTOCK.PESO_ACUMULADO <= 0.8 THEN 'A'
	  WHEN TBSTOCK.PESO_ACUMULADO > 0.8 AND TBSTOCK.PESO_ACUMULADO <= 0.95 THEN 'B'
	  WHEN TBSTOCK.PESO_ACUMULADO > 0.95 AND TBSTOCK.PESO_ACUMULADO <= 1 THEN 'C'
	  ELSE 'C' END AS ABC_STOCK_VALUE,
	   (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))   AS FECHA_CIERRE
	--  INTO EBIZ_ABC_STOCK
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,TB1.ESTADO_MATERIAL,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.MARCA, TB1.STOCK_DOLARES DESC) AS PESO_ACUMULADO
FROM (

SELECT TB1.marca, TB1.COD_MATERIAL,TB1.ESTADO_MATERIAL, TB1.STOCK_DOLARES, TB2.STOCK_DOLARES AS STOCK_MARCA, 
CASE WHEN TB2.STOCK_DOLARES = NULL THEN 0
 WHEN TB2.STOCK_DOLARES = 0 THEN 0
ELSE (CAST(TB1.STOCK_DOLARES AS decimal(18,10)) / CAST(TB2.STOCK_DOLARES AS decimal(18,10)) ) END AS PESO 
FROM #TABLA_STOCK_ABC_LOGICA_1_12MESES TB1 

LEFT JOIN #TABLA_STOCK_ABC_LOGICA_2_12MESES TB2 ON TB1.marca =TB2.marca ) TB1 ) TBSTOCK	


INSERT INTO EBIZ_ABC_COSTO_INTERNO_12MESES
SELECT DISTINCT MARCA,COD_MATERIAL,0,0,'C',(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
FROM ebiz_materiales 
where cod_material not in (
SELECT DISTINCT COD_MATERIAL
FROM EBIZ_ABC_COSTO_INTERNO_12MESES 
WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) ) 
and origen = 'hana'

INSERT INTO EBIZ_ABC_STOCK_12MESES
SELECT DISTINCT MARCA,COD_MATERIAL,0,0,TEXT_STATUS,'C',(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
FROM ebiz_materiales 
where cod_material not in (
SELECT DISTINCT COD_MATERIAL
FROM EBIZ_ABC_STOCK_12MESES 
WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) ) 
and origen = 'hana'






DROP TABLE #TABLA_STOCK_ABC_LOGICA_1_12MESES

DROP TABLE #TABLA_STOCK_ABC_LOGICA_2_12MESES

DROP TABLE #TABLA_COSTO_ABC_VENTAS_12MESES

DROP TABLE #TABLA_COSTO_ABC_VENTAS_2_12MESES

DROP TABLE #TABLA_COSTO_ABC_LOGICA_1_12MESES

DROP TABLE #TABLA_COSTO_ABC_LOGICA_2_12MESES



-------------------------------------- 36 MESES -----------------------------------------------



SELECT B.MARCA,A.COD_MATERIAL,B.TEXT_STATUS AS ESTADO_MATERIAL, SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_BLOQUEADO + ECS_CALIDAD) AS STOCK_DOLARES
into #TABLA_STOCK_ABC_LOGICA_1_36MESES
FROM EBIZ_STOCK_AL_CIERRE A
LEFT JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE origen = 'hana'
AND YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))
GROUP BY B.MARCA,A.COD_MATERIAL,B.TEXT_STATUS

SELECT B.marca, SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_BLOQUEADO + ECS_CALIDAD) AS STOCK_DOLARES
into #TABLA_STOCK_ABC_LOGICA_2_36MESES
FROM EBIZ_STOCK_AL_CIERRE A
INNER JOIN EBIZ_MATERIALES B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE ORIGEN = 'hana'
and  YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))
GROUP BY B.marca


--DROP TABLE #TABLA_COSTO_ABC_VENTAS

SELECT A.COD_MATERIAL AS COD_MATERIAL, COSTO_INTERNO as costo_interno
INTO #TABLA_COSTO_ABC_VENTAS_36MESES
FROM ebiz_ventas A
--INNER JOIN ebiz_materiales B ON A.COD_MATERIAL_CUSTOM = B.COD_MATERIAL_CUSTOM
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-36,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')


--DROP TABLE #TABLA_COSTO_ABC_VENTAS_2

SELECT A.*, B.marca
into #TABLA_COSTO_ABC_VENTAS_2_36MESES
FROM #TABLA_COSTO_ABC_VENTAS_36MESES A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE  A.COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_articulo like '%Ing.&Egr.Financieros%' or grupo_articulo like 'Servicio Logistico%') )



--DROP TABLE #TABLA_COSTO_ABC_LOGICA_1

SELECT marca,COD_MATERIAL, SUM(COSTO_INTERNO) AS COSTO_INTERNO
INTO #TABLA_COSTO_ABC_LOGICA_1_36MESES
FROM #TABLA_COSTO_ABC_VENTAS_2_36MESES
GROUP BY  marca,COD_MATERIAL

--DROP TABLE #TABLA_COSTO_ABC_LOGICA_2

SELECT marca, SUM(COSTO_INTERNO) AS COSTO_INTERNO
INTO #TABLA_COSTO_ABC_LOGICA_2_36MESES
FROM #TABLA_COSTO_ABC_VENTAS_2_36MESES 
GROUP BY  marca


DELETE FROM EBIZ_ABC_COSTO_INTERNO_36MESES WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

DELETE FROM EBIZ_ABC_STOCK_36MESES WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

INSERT INTO EBIZ_ABC_COSTO_INTERNO_36MESES
SELECT TBCOSTO.marca, TBCOSTO.COD_MATERIAL, TBCOSTO.PESO, TBCOSTO.PESO_ACUMULADO,
CASE WHEN TBCOSTO.PESO_ACUMULADO >= 0 AND TBCOSTO.PESO_ACUMULADO <= 0.8 THEN 'A'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.8 AND TBCOSTO.PESO_ACUMULADO <= 0.95 THEN 'B'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.95 AND TBCOSTO.PESO_ACUMULADO <= 1 THEN 'C'
	  ELSE 'C' END AS ABC_COSTO_VALUE,
	  (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))  AS FECHA_CIERRE
--INTO 
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.MARCA, TB1.COSTO_INTERNO DESC) AS PESO_ACUMULADO
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.COSTO_INTERNO, TB2.COSTO_INTERNO AS COSTO_INTERNO_MARCA, 
CASE WHEN TB2.COSTO_INTERNO = NULL THEN 0
 WHEN TB2.COSTO_INTERNO = 0 THEN 0
ELSE (CAST(TB1.COSTO_INTERNO AS decimal(18,10)) / CAST(TB2.COSTO_INTERNO AS decimal(18,10)) ) END AS PESO 

FROM #TABLA_COSTO_ABC_LOGICA_1_36MESES TB1


INNER JOIN #TABLA_COSTO_ABC_LOGICA_2_36MESES TB2 ON TB1.marca = TB2.marca ) TB1 ) TBCOSTO




INSERT INTO EBIZ_ABC_STOCK_36MESES
SELECT TBSTOCK.marca, TBSTOCK.COD_MATERIAL, TBSTOCK.PESO, TBSTOCK.PESO_ACUMULADO,TBSTOCK.ESTADO_MATERIAL,
CASE WHEN TBSTOCK.PESO_ACUMULADO >= 0 AND TBSTOCK.PESO_ACUMULADO <= 0.8 THEN 'A'
	  WHEN TBSTOCK.PESO_ACUMULADO > 0.8 AND TBSTOCK.PESO_ACUMULADO <= 0.95 THEN 'B'
	  WHEN TBSTOCK.PESO_ACUMULADO > 0.95 AND TBSTOCK.PESO_ACUMULADO <= 1 THEN 'C'
	  ELSE 'C' END AS ABC_STOCK_VALUE,
	   (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))   AS FECHA_CIERRE
	--  INTO EBIZ_ABC_STOCK
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,TB1.ESTADO_MATERIAL,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.MARCA, TB1.STOCK_DOLARES DESC) AS PESO_ACUMULADO
FROM (

SELECT TB1.marca, TB1.COD_MATERIAL,TB1.ESTADO_MATERIAL, TB1.STOCK_DOLARES, TB2.STOCK_DOLARES AS STOCK_MARCA, 
CASE WHEN TB2.STOCK_DOLARES = NULL THEN 0
 WHEN TB2.STOCK_DOLARES = 0 THEN 0
ELSE (CAST(TB1.STOCK_DOLARES AS decimal(18,10)) / CAST(TB2.STOCK_DOLARES AS decimal(18,10)) ) END AS PESO 
FROM #TABLA_STOCK_ABC_LOGICA_1_36MESES TB1 

LEFT JOIN #TABLA_STOCK_ABC_LOGICA_2_36MESES TB2 ON TB1.marca =TB2.marca ) TB1 ) TBSTOCK	


INSERT INTO EBIZ_ABC_COSTO_INTERNO_36MESES
SELECT DISTINCT MARCA,COD_MATERIAL,0,0,'C',(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
FROM ebiz_materiales 
where cod_material not in (
SELECT DISTINCT COD_MATERIAL
FROM EBIZ_ABC_COSTO_INTERNO_36MESES 
WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) ) 
and origen = 'hana'

INSERT INTO EBIZ_ABC_STOCK_36MESES
SELECT DISTINCT MARCA,COD_MATERIAL,0,0,TEXT_STATUS,'C',(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
FROM ebiz_materiales 
where cod_material not in (
SELECT DISTINCT COD_MATERIAL
FROM EBIZ_ABC_STOCK_36MESES
WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) ) 
and origen = 'hana'






DROP TABLE #TABLA_STOCK_ABC_LOGICA_1_36MESES

DROP TABLE #TABLA_STOCK_ABC_LOGICA_2_36MESES

DROP TABLE #TABLA_COSTO_ABC_VENTAS_36MESES

DROP TABLE #TABLA_COSTO_ABC_VENTAS_2_36MESES

DROP TABLE #TABLA_COSTO_ABC_LOGICA_1_36MESES

DROP TABLE #TABLA_COSTO_ABC_LOGICA_2_36MESES




----------------------------- TERMINA AQUI ------------------------------------------------------
 
----- INFORMACION COMPLEMENTARIA ----

DECLARE @CURRENT_DAY DATE ;
SET @CURRENT_DAY = DATEADD(DAY, -1, GETDATE());


SELECT DISTINCT B.cod_material_hana AS COD_MATERIAL,A.FECHA_CREACION
INTO #EBIZ_MATERIALES_FECHA_CREACION_R3
FROM COM_DIM_MATERIALES A
INNER JOIN (

SELECT DISTINCT COD_MATERIAL,cod_material_hana
FROM ebiz_materiales
WHERE ORIGEN = 'r3' )B ON A.COD_MATERIAL = B.COD_MATERIAL


SELECT DISTINCT COD_MATERIAL,FECHA_CREACION
INTO #EBIZ_MATERIALES_FECHA_CREACION_HANA
FROM ebiz_materiales 
WHERE COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL 
FROM #EBIZ_MATERIALES_FECHA_CREACION_R3 )
AND  origen = 'hana'

SELECT *
INTO #EBIZ_MATERIALES_FECHA_CREACION
FROM (
SELECT *
FROM #EBIZ_MATERIALES_FECHA_CREACION_HANA
UNION ALL
SELECT *
FROM #EBIZ_MATERIALES_FECHA_CREACION_R3) TB1


SELECT B.cod_material_hana AS COD_MATERIAL_CUSTOM,MAX(FECHA_COMPLETA) AS FECHA_ULTIMA_VENTA
into #EBIZ_ULTIMA_VENTA
FROM (SELECT *
FROM ebiz_ventas
WHERE  VALOR_ANTES_IVA > 0
AND fecha_factura <= @CURRENT_DAY) A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL_CUSTOM = B.COD_MATERIAL_CUSTOM
GROUP BY B.cod_material_hana



SELECT RTRIM(COD_MATERIAL) AS COD_MATERIAL_CUSTOM,MAX(FECHA_CONTABLE) AS FECHA_ULTIMA_COMPRA,'101' AS MOVIMIENTO
INTO #EBIZ_ULTIMA_COMPRA 
FROM (SELECT COD_LOGISTICO AS COD_COMPRA,(COD_MATERIAL * 1) AS COD_MATERIAL,FECHA_CONTABLE
FROM EBIZ_MOVIMIENTOS_LOGISTICOS
WHERE MOVIMIENTO IN ('101','501')
--AND (COD_LOGISTICO LIKE '30%' OR COD_LOGISTICO LIKE '38%' OR COD_LOGISTICO LIKE '42%')
AND FECHA_CONTABLE <= @CURRENT_DAY) A
--INNER JOIN ebiz_materiales B ON cast(A.COD_MATERIAL as nvarchar) = rtrim(B.COD_MATERIAL_CUSTOM) 
--and B.COD_MATERIAL_CUSTOM not like '%dummy%'
GROUP BY COD_MATERIAL

INSERT INTO #EBIZ_ULTIMA_COMPRA
SELECT RTRIM(CAST(TB1.COD_MATERIAL AS nvarchar)) AS COD_MATERIAL_CUSTOM,MAX(FECHA_CONTABLE) AS FECHA_ULTIMA_COMPRA,'309' AS MOVIMIENTO

FROM (

SELECT A.COD_LOGISTICO,A.COD_MATERIAL,FECHA_CONTABLE

FROM

(
SELECT COD_LOGISTICO,(COD_MATERIAL * 1) AS COD_MATERIAL ,FECHA_CONTABLE
FROM EBIZ_MOVIMIENTOS_LOGISTICOS
WHERE MOVIMIENTO = '101'
AND FECHA_CONTABLE <= @CURRENT_DAY
) A 

INNER JOIN (SELECT 
COD_LOGISTICO AS COD_COMPRA,
(COD_MATERIAL * 1) AS COD_MATERIAL,
MAX(FECHA_CONTABLE) AS FECHA_MAX

FROM EBIZ_MOVIMIENTOS_LOGISTICOS
WHERE MOVIMIENTO = '309' AND MONTO < 0 
AND FECHA_CONTABLE <= @CURRENT_DAY
GROUP BY COD_LOGISTICO,
COD_MATERIAL
) B ON A.COD_MATERIAL = B.COD_MATERIAL
WHERE FECHA_CONTABLE <= FECHA_MAX

) TB1
WHERE CAST(TB1.COD_MATERIAL AS nvarchar) not in (SELECT DISTINCT CAST(COD_MATERIAL_CUSTOM AS nvarchar) FROM #EBIZ_ULTIMA_COMPRA )
GROUP BY  TB1.COD_MATERIAL

INSERT INTO #EBIZ_ULTIMA_COMPRA
SELECT RTRIM(CAST(COD_MATERIAL_HANA AS varchar)) AS COD_MATERIAL_HANA,CAST(MAX(FECHA_CONTABLE) AS DATE) AS FECHA_CONTABLE,'101'  AS MOVIMIENTO
FROM EBIZ_MOVIMIENTOS_LOGISTICOS_R3
WHERE RTRIM(COD_MATERIAL_HANA) NOT IN (SELECT DISTINCT CAST(COD_MATERIAL_CUSTOM AS nvarchar) FROM #EBIZ_ULTIMA_COMPRA )
AND (COD_LOGISTICO LIKE '47%' OR COD_LOGISTICO LIKE '49%')
GROUP BY COD_MATERIAL_HANA



INSERT INTO #EBIZ_ULTIMA_COMPRA
SELECT RTRIM(B.cod_material_hana) AS COD_MATERIAL_CUSTOM,MAX(FECHA_ULTIMA_COMPRA) AS FECHA_ULTIMA_COMPRA,'101'  AS MOVIMIENTO
FROM (SELECT COD_MATERIAL AS COD_MATERIAL_CUSTOM ,FECHA_ULTIMA_COMPRA
FROM EBIZ_MATERIALES_AC_DATA_EXTRA
WHERE MONTH(FECHA_CIERRE) = 7 AND YEAR(FECHA_CIERRE) = 2021) A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL_CUSTOM = B.COD_MATERIAL_CUSTOM
AND A.COD_MATERIAL_CUSTOM NOT IN (SELECT DISTINCT CAST(COD_MATERIAL_CUSTOM AS nvarchar) FROM #EBIZ_ULTIMA_COMPRA )
GROUP BY B.cod_material_hana



DELETE FROM EBIZ_MATERIALES_AC_DATA_EXTRA WHERE YEAR(FECHA_CIERRE) = YEAR(@CURRENT_DAY) 
AND MONTH(FECHA_CIERRE) = MONTH(@CURRENT_DAY)


INSERT INTO EBIZ_MATERIALES_AC_DATA_EXTRA
SELECT A.COD_MATERIAL,A.FECHA_CREACION,B.FECHA_ULTIMA_VENTA,C.FECHA_ULTIMA_COMPRA,
@CURRENT_DAY AS FECHA_CIERRE,MOVIMIENTO
FROM #EBIZ_MATERIALES_FECHA_CREACION A
LEFT JOIN #EBIZ_ULTIMA_VENTA B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
LEFT JOIN #EBIZ_ULTIMA_COMPRA C ON A.COD_MATERIAL = C.COD_MATERIAL_CUSTOM


UPDATE EBIZ_MATERIALES_AC_DATA_EXTRA
SET
FECHA_ULTIMA_COMPRA = '1900-01-01' 
WHERE FECHA_ULTIMA_COMPRA IS NULL


DROP TABLE #EBIZ_MATERIALES_FECHA_CREACION_R3

DROP TABLE #EBIZ_MATERIALES_FECHA_CREACION_HANA

DROP TABLE #EBIZ_MATERIALES_FECHA_CREACION

DROP TABLE #EBIZ_ULTIMA_VENTA

DROP TABLE #EBIZ_ULTIMA_COMPRA











GO


