USE [HIVIMAR_EBIZ]
GO

/****** Object:  StoredProcedure [dbo].[STP_PROYECCION_STOCK]    Script Date: 28/3/2022 10:46:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








ALTER PROCEDURE [dbo].[STP_PROYECCION_STOCK] AS
--DROP TABLE #STOCK_PROYECCION_INICIAL

DELETE
FROM ebiz_ppto_compras_logistica
WHERE MES IS NULL


DELETE
FROM ebiz_ppto_ventas_logistica
WHERE MES IS NULL

update ebiz_ppto_compras_logistica
set
PPTO_COMPRAS_LOGISTICA = 0
WHERE PPTO_COMPRAS_LOGISTICA IS NULL


update ebiz_ppto_ventas_logistica
set
PPTO_VTA_LOGISTICA = 0
WHERE PPTO_VTA_LOGISTICA IS NULL
	

SELECT B.cod_grupo_articulo, 
	  YEAR((DATEADD(DAY, -1, GETDATE()))) AS AÑO, 
	  MONTH((DATEADD(DAY, -1, GETDATE()))) AS MES, 
	  B.marca, 
	  SUM(UND_LIBRE_UTILICACION + UND_TRASLADO +  UND_CALIDAD + UND_BLOQUEADO) AS stock_unidad,
	  SUM(ECS_LIBRE_UTILICACION + ECS_TRASLADO + ECS_CALIDAD + ECS_BLOQUEADO) AS stock_dolares,
	 (DATEADD(DAY, -1, GETDATE())) as FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL
FROM EBIZ_STOCK_AL_CIERRE A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE MONTH(FECHA_CIERRE) =  MONTH(DATEADD(MONTH, -1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', GETDATE()), '19000101')) )
AND YEAR(FECHA_CIERRE) = YEAR(DATEADD(MONTH, -1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', GETDATE()), '19000101')))
GROUP BY  B.cod_grupo_articulo, 
	  YEAR(FECHA_CIERRE),
	  MONTH(FECHA_CIERRE), 
	  B.marca


--SELECT * FROM #PPTO_COMPRAS_LOGICA
--DROP TABLE #PPTO_COMPRAS_LOGICA

SELECT A.cod_grupo_articulo,A.marca,AÑO,MES,PPTO_COMPRAS_LOGISTICA AS FOB,

CASE 
				 WHEN monto_factor_gasto is NULL THEN 1
				 ELSE monto_factor_gasto END AS monto_factor_gasto, 

				( CASE 
				 WHEN monto_factor_gasto is NULL THEN 1
				 ELSE monto_factor_gasto END ) * PPTO_COMPRAS_LOGISTICA AS COSTO_LANDED_PPTO,
				   (DATEADD(DAY, -1, GETDATE())) as FECHA_CIERRE,
				   CAST(CONCAT(AÑO,'-',MES,'-','01 01:01:00.000') AS datetime) AS FECHA_LOGICA
INTO #PPTO_COMPRAS_LOGICA
FROM ebiz_ppto_compras_logistica A

LEFT JOIN ebiz_factor_gasto B ON A.cod_grupo_articulo = B.cod_grupo_articulo
							  AND A.marca = B.marca
WHERE A.AÑO =  YEAR((DATEADD(DAY, -1, GETDATE())))
	  --DROP TABLE #PPTO_VENTAS_LOGICA

	      SELECT *, 
		 PPTO_VTA_LOGISTICA AS ESTIMADO_VENTAS,   
		 (DATEADD(DAY, -1, GETDATE())) as FECHA_CIERRE,
		 (PPTO_VTA_LOGISTICA - (PPTO_VTA_LOGISTICA * margen) ) AS COSTO_INTERNO,
		 CAST(CONCAT(AÑO,'-',MES,'-','01 01:01:00.000') AS datetime) AS FECHA_LOGICA
		 INTO #PPTO_VENTAS_LOGICA
         FROM ebiz_ppto_ventas_logistica
		 WHERE [AÑO ]=YEAR((DATEADD(DAY, -1, GETDATE())))

	  INSERT INTO #STOCK_PROYECCION_INICIAL						  
	  SELECT cod_grupo_articulo,AÑO,MONTH( (DATEADD(DAY, -1, GETDATE()))) ,marca,0,0,(DATEADD(DAY, -1, GETDATE())) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(DAY, -1, GETDATE()))) AND MES = MONTH( (DATEADD(DAY, -1, GETDATE()))) 

	  INSERT INTO #STOCK_PROYECCION_INICIAL						  
	  SELECT cod_grupo_articulo,AÑO,MONTH( (DATEADD(DAY, -1, GETDATE()))) ,marca,0,0,(DATEADD(DAY, -1, GETDATE())) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(DAY, -1, GETDATE()))) AND MES = MONTH( (DATEADD(DAY, -1, GETDATE()))) 


	 -- DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_1

	  SELECT cod_grupo_articulo,AÑO,MES,marca,SUM(STOCK_UNIDAD) AS STOCK_UNIDAD, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(DAY, -1, GETDATE())) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_1
	  FROM #STOCK_PROYECCION_INICIAL
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca



	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_1

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_1
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_1 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO

--BASE MES 2 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_2

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_2
		FROM #STOCK_PROYECCION_BASE_MES_1
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_2						  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_2						  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_3

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_3
	  FROM #STOCK_PROYECCION_LOGICA_2
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_2

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_2
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_3 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO


		--BASE MES 3 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_4

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_4
		FROM #STOCK_PROYECCION_BASE_MES_2
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_4						  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_4					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_5

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +2, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_5
	  FROM #STOCK_PROYECCION_LOGICA_4
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_3

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_3
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_5 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
	
					
							--BASE MES 4 ---
		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_6

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_6
		FROM #STOCK_PROYECCION_BASE_MES_3
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_6						  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +1, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_6					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_7

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +3, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_7
	  FROM #STOCK_PROYECCION_LOGICA_6
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_4

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_4
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_7 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
			
			--BASE MES 5 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_8

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_8
		FROM #STOCK_PROYECCION_BASE_MES_4
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_8						  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_8					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_9

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +4, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_9
	  FROM #STOCK_PROYECCION_LOGICA_8
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_5

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_5
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_9 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
			
				--BASE MES 6 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_10
		FROM #STOCK_PROYECCION_BASE_MES_5
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_10						  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_10					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +5, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_11
	  FROM #STOCK_PROYECCION_LOGICA_10
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_6
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_11 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
										

	--BASE MES 7 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_12
		FROM #STOCK_PROYECCION_BASE_MES_6
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_12				  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_12					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +6, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_13
	  FROM #STOCK_PROYECCION_LOGICA_12
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_7
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_13 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
										


--BASE MES 8 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_14
		FROM #STOCK_PROYECCION_BASE_MES_7
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_14				  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_14					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +7, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_15
	  FROM #STOCK_PROYECCION_LOGICA_14
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_8
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_15 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
										


--BASE MES 9 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_16
		FROM #STOCK_PROYECCION_BASE_MES_8
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_16				  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_16					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +8, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_17
	  FROM #STOCK_PROYECCION_LOGICA_16
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_9
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_17 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
										
--BASE MES 10 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_18
		FROM #STOCK_PROYECCION_BASE_MES_9
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_18				  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_18					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +9, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_19
	  FROM #STOCK_PROYECCION_LOGICA_18
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_10
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_19 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO
	
	--BASE MES 11 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_20
		FROM #STOCK_PROYECCION_BASE_MES_10
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_20				  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_20					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +10, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_21
	  FROM #STOCK_PROYECCION_LOGICA_20
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_11
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_21 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO									
	--BASE MES 12 ---

		 
		--DROP TABLE #STOCK_PROYECCION_LOGICA_10

		SELECT 
		cod_grupo_articulo, 
		YEAR((DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS AÑO,
		MONTH((DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')) )) AS MES,
		marca,
		PROYECCION_STOCK AS STOCK_DOLARES,
		(DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))  AS FECHA_CIERRE
		INTO #STOCK_PROYECCION_LOGICA_22
		FROM #STOCK_PROYECCION_BASE_MES_11
	
	

	  INSERT INTO #STOCK_PROYECCION_LOGICA_22				  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_COMPRAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 

	   INSERT INTO #STOCK_PROYECCION_LOGICA_22					  
	  SELECT cod_grupo_articulo,
	  YEAR((DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS AÑO,
	  MONTH((DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) AS MES,
	  marca,0,
	  (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  FROM #PPTO_VENTAS_LOGICA
	  WHERE AÑO = YEAR( (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 
	  AND MES = MONTH( (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101')))) 


	 
	  --DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

	  SELECT cod_grupo_articulo,AÑO,MES,marca, SUM(STOCK_DOLARES) AS STOCK_DOLARES, 
	  (DATEADD(MONTH, +11, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', (DATEADD(DAY, -1, GETDATE()))), '19000101'))) AS FECHA_CIERRE
	  INTO #STOCK_PROYECCION_INICIAL_LOGICA_23
	  FROM #STOCK_PROYECCION_LOGICA_22
	  GROUP BY cod_grupo_articulo,AÑO,MES,marca

	  --SELECT *
	  --FROM #STOCK_PROYECCION_INICIAL_LOGICA_3

	  --DROP TABLE #STOCK_PROYECCION_BASE_MES_6

	  SELECT A.cod_grupo_articulo, 
	  A.marca, 
	  CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END AS STOCK_DOLARES, 
	  A.FECHA_CIERRE,
	  MONTH(A.FECHA_CIERRE) AS MES,
	  YEAR(A.FECHA_CIERRE) AS AÑO,
	  FOB,
	  monto_factor_gasto,
	  CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END AS COSTO_LANDED_PPTO, 
	  margen,
	  CASE WHEN PPTO_VTA_LOGISTICA IS NULL THEN 0
	  ELSE PPTO_VTA_LOGISTICA END AS PPTO_VTA_LOGISTICA,
	  ESTIMADO_VENTAS,
	  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END AS COSTO_INTERNO,
	  CASE 
	  WHEN ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) < 0 THEN 0
	  ELSE ( CASE WHEN A.STOCK_DOLARES IS NULL THEN 0
	  ELSE A.STOCK_DOLARES END + CASE WHEN COSTO_LANDED_PPTO IS NULL THEN 0
	  ELSE COSTO_LANDED_PPTO END -  CASE WHEN COSTO_INTERNO IS NULL THEN 0
	  ELSE COSTO_INTERNO END) END  AS PROYECCION_STOCK

	  INTO #STOCK_PROYECCION_BASE_MES_12
	  FROM #STOCK_PROYECCION_INICIAL_LOGICA_23 A

	  LEFT JOIN #PPTO_COMPRAS_LOGICA B ON A.cod_grupo_articulo = B.cod_grupo_articulo
										AND A.marca = B.marca
										AND MONTH(A.FECHA_CIERRE) = B.MES
										AND YEAR(A.FECHA_CIERRE) = B.AÑO
	   LEFT JOIN #PPTO_VENTAS_LOGICA C ON A.cod_grupo_articulo = C.cod_grupo_articulo
										AND A.marca = C.marca
										AND MONTH(A.FECHA_CIERRE) = C.MES
										AND YEAR(A.FECHA_CIERRE) = C.AÑO	


										DELETE FROM EBIZ_PROYECCION_STOCK_FUTURO

										INSERT INTO EBIZ_PROYECCION_STOCK_FUTURO
										SELECT *
										FROM (

										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_1
										
										union all 	

										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_2

										union all

										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_3

										union all 	

										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_4

										union all

										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_5

										union all

										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_6
										union all
										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_7
										union all
										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_8 
										
										union all
										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_9
										
										union all
										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_10

										union all
										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_11

										union all
										SELECT *
										FROM #STOCK_PROYECCION_BASE_MES_12
										) TB1


DROP TABLE #STOCK_PROYECCION_INICIAL

DROP TABLE #PPTO_COMPRAS_LOGICA

DROP TABLE #PPTO_VENTAS_LOGICA

 DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_1

  DROP TABLE #STOCK_PROYECCION_BASE_MES_1

DROP TABLE #STOCK_PROYECCION_LOGICA_2

 DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_3

DROP TABLE #STOCK_PROYECCION_BASE_MES_2

DROP TABLE #STOCK_PROYECCION_LOGICA_4

DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_5

DROP TABLE #STOCK_PROYECCION_BASE_MES_3

DROP TABLE #STOCK_PROYECCION_LOGICA_6

DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_7

DROP TABLE #STOCK_PROYECCION_BASE_MES_4

DROP TABLE #STOCK_PROYECCION_LOGICA_8

 DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_9
 DROP TABLE #STOCK_PROYECCION_BASE_MES_5

DROP TABLE #STOCK_PROYECCION_LOGICA_10

DROP TABLE #STOCK_PROYECCION_INICIAL_LOGICA_11

DROP TABLE #STOCK_PROYECCION_BASE_MES_6









GO


