USE [HIVIMAR_EBIZ]
GO

/****** Object:  StoredProcedure [dbo].[STP_STOCK_PROFILER]    Script Date: 28/3/2022 10:47:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





ALTER PROCEDURE [dbo].[STP_STOCK_PROFILER]
AS
SELECT A.COD_MATERIAL AS COD_MATERIAL, VALOR_ANTES_IVA as VTAS
INTO #TABLA_STOCK_PROFILER_VENTAS
FROM ebiz_ventas A
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')


SELECT A.*, B.marca
into #TABLA_STOCK_PROFILER_VENTAS_2
FROM #TABLA_STOCK_PROFILER_VENTAS A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE  A.COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_articulo like '%Ing.&Egr.Financieros%' or grupo_articulo like 'Servicio Logistico%') )

SELECT marca,COD_MATERIAL, SUM(VTAS) AS VTAS
INTO #TABLA_STOCK_PROFILER_LOGICA_1
FROM #TABLA_STOCK_PROFILER_VENTAS_2 
GROUP BY  marca,COD_MATERIAL



SELECT marca, SUM(VTAS) AS VTAS
INTO #TABLA_STOCK_PROFILER_LOGICA_2
FROM #TABLA_STOCK_PROFILER_VENTAS_2 
GROUP BY  marca

---NUMERO CLIENTES ---

SELECT A.COD_MATERIAL AS COD_MATERIAL, COUNT(DISTINCT COD_CLIENTE) as NUM_CLIENTES
INTO #TABLA_STOCK_PROFILER_VENTAS_3
FROM ebiz_ventas A
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')
AND VALOR_ANTES_IVA > 0
GROUP BY A.COD_MATERIAL


DELETE FROM EBIZ_STOCK_PROFILER_VTAS WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

INSERT INTO EBIZ_STOCK_PROFILER_VTAS
SELECT TBCOSTO.marca, TBCOSTO.COD_MATERIAL, TBCOSTO.PESO, TBCOSTO.PESO_ACUMULADO,
CASE WHEN TBCOSTO.PESO_ACUMULADO >= 0 AND TBCOSTO.PESO_ACUMULADO <= 0.2 THEN 'A'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.2 AND TBCOSTO.PESO_ACUMULADO <= 0.8 THEN 'B'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.8 AND TBCOSTO.PESO_ACUMULADO <= 0.95 THEN 'C'
	  WHEN TBCOSTO.PESO_ACUMULADO > 1 AND TBCOSTO.PESO_ACUMULADO = 0 THEN 'O'
	  ELSE 'D' END AS STOCK_PROFILER_VALUE,
	  (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))  AS FECHA_CIERRE,
	  	 CASE WHEN NUM_CLIENTES > 0 AND NUM_CLIENTES <= 1 THEN '9'
		  WHEN NUM_CLIENTES >= 2 AND NUM_CLIENTES <= 4 THEN '2'
		  WHEN NUM_CLIENTES >= 5 THEN '1'
		  ELSE '9' END AS STOCK_PROFILER_VALUE_2
--INTO EBIZ_STOCK_PROFILER_VTAS
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.marca, TB1.VTAS DESC) AS PESO_ACUMULADO
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.VTAS, TB2.VTAS AS COSTO_INTERNO_MARCA, 
CASE WHEN TB2.VTAS = NULL THEN 0
 WHEN TB2.VTAS = 0 THEN 0
ELSE (CAST(TB1.VTAS AS decimal(18,10)) / CAST(TB2.VTAS AS decimal(18,10)) ) END AS PESO 

FROM #TABLA_STOCK_PROFILER_LOGICA_1 TB1


INNER JOIN #TABLA_STOCK_PROFILER_LOGICA_2 TB2 ON TB1.marca = TB2.marca ) TB1 ) TBCOSTO

LEFT JOIN #TABLA_STOCK_PROFILER_VENTAS_3 TB2 ON TBCOSTO.COD_MATERIAL = TB2.COD_MATERIAL

DROP TABLE #TABLA_STOCK_PROFILER_VENTAS

DROP TABLE #TABLA_STOCK_PROFILER_VENTAS_2

DROP TABLE #TABLA_STOCK_PROFILER_LOGICA_2

DROP TABLE #TABLA_STOCK_PROFILER_LOGICA_1

DROP TABLE #TABLA_STOCK_PROFILER_VENTAS_3


-------------------- STOCK PROFILER CONSUMO -----------------------------------



SELECT A.COD_MATERIAL AS COD_MATERIAL, SUM(VALOR_ANTES_IVA) as VTAS
INTO #TB_STOCK_PROFILER_CONSUMO_1
FROM ebiz_ventas A
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')

GROUP BY COD_MATERIAL


SELECT A.*,B.marca
INTO #TB_STOCK_PROFILER_CONSUMO_2
FROM #TB_STOCK_PROFILER_CONSUMO_1 A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE  A.COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_precio_material like '%Servicios De Taller%' or grupo_articulo like '%Servicio de Ingenier%' 
						OR grupo_articulo like '%Ing.&Egr.Financieros%' or grupo_articulo like 'Servicio Logistico%'))


SELECT COD_MATERIAL AS COD_MATERIAL, SUM((COSTO + (COSTO * 0.25))) as VTAS
INTO #TB_STOCK_PROFILER_CONSUMO_3
FROM EBIZ_PICKINGS
WHERE COD_PEDIDO IN (SELECT DISTINCT COD_PEDIDO
FROM ebiz_ventas
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0)  
AND  COD_MATERIAL IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_precio_material like '%Servicios De Taller%' or grupo_articulo like '%Servicio de Ingenier%')))

GROUP BY COD_MATERIAL

SELECT A.*,B.marca
INTO #TB_STOCK_PROFILER_CONSUMO_4
FROM #TB_STOCK_PROFILER_CONSUMO_3 A
INNER JOIN ebiz_materiales B ON A.COD_MATERIAL = B.COD_MATERIAL_CUSTOM
WHERE (A.COD_MATERIAL NOT LIKE '600%' AND A.COD_MATERIAL NOT LIKE '200%')






SELECT COD_MATERIAL,marca,SUM(VTAS) AS VTAS
INTO #TB_STOCK_PROFILER_CONSUMO_MATERIAL
FROM 
(
SELECT *
FROM #TB_STOCK_PROFILER_CONSUMO_2

UNION ALL

SELECT *
FROM #TB_STOCK_PROFILER_CONSUMO_4
  )TB1

GROUP BY COD_MATERIAL,marca

SELECT marca,SUM(VTAS) AS VTAS
INTO #TB_STOCK_PROFILER_CONSUMO_MARCA
FROM 
(
SELECT *
FROM #TB_STOCK_PROFILER_CONSUMO_2

UNION ALL

SELECT *
FROM #TB_STOCK_PROFILER_CONSUMO_4
  )TB1

GROUP BY marca


------------ NUM CLIENTES ---------------

SELECT *
INTO #TABLA_STOCK_PROFILER_VENTAS_CLIENTES_1
FROM ( 

SELECT DISTINCT A.COD_MATERIAL AS COD_MATERIAL, COD_CLIENTE as NUM_CLIENTES
FROM ebiz_ventas A
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0) 
and a.COD_MATERIAL_CUSTOM NOT like '%6000120%' and a.COD_MOTIVO_PEDIDO not like '%Z23%'
AND  cod_cliente not in ('1000347','1000348',
'1000349','1000447','1100','1200','1300',
'1400','1500','1600','1700','1800','1900',
'460339','r3-0000250110','r3-0000461864','460339')
AND VALOR_ANTES_IVA > 0


UNION ALL

SELECT DISTINCT COD_MATERIAL AS COD_MATERIAL, COD_CLIENTE 
FROM EBIZ_PICKINGS
WHERE COD_PEDIDO IN (SELECT DISTINCT COD_PEDIDO
FROM ebiz_ventas
WHERE fecha_factura >=  DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-12,GETDATE())),0)
AND fecha_factura < DATEADD(mm, DATEDIFF(mm,0,GETDATE()),0)  
AND  COD_MATERIAL IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_precio_material like '%Servicios De Taller%' or grupo_articulo like '%Servicio de Ingenier%')))
AND COSTO > 0
) TB1


SELECT COD_MATERIAL,COUNT(DISTINCT NUM_CLIENTES) AS NUM_CLIENTES
INTO #TABLA_STOCK_PROFILER_VENTAS_CLIENTES_2
FROM #TABLA_STOCK_PROFILER_VENTAS_CLIENTES_1 A
WHERE  A.COD_MATERIAL NOT IN (SELECT DISTINCT COD_MATERIAL_CUSTOM 
						FROM EBIZ_MATERIALES 
						WHERE ORIGEN = 'hana' 
						AND (grupo_precio_material like '%Servicios De Taller%' or grupo_articulo like '%Servicio de Ingenier%' 
						OR grupo_articulo like '%Ing.&Egr.Financieros%' or grupo_articulo like 'Servicio Logistico%'))
GROUP BY COD_MATERIAL




DELETE FROM EBIZ_STOCK_PROFILER_VTAS_TALLER WHERE YEAR(FECHA_CIERRE) = YEAR(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0)) 
AND MONTH(FECHA_CIERRE) = MONTH(DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))

INSERT INTO EBIZ_STOCK_PROFILER_VTAS_TALLER
SELECT TBCOSTO.marca, TBCOSTO.COD_MATERIAL, TBCOSTO.PESO, TBCOSTO.PESO_ACUMULADO,
CASE WHEN TBCOSTO.PESO_ACUMULADO >= 0 AND TBCOSTO.PESO_ACUMULADO <= 0.2 THEN 'A'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.2 AND TBCOSTO.PESO_ACUMULADO <= 0.8 THEN 'B'
	  WHEN TBCOSTO.PESO_ACUMULADO > 0.8 AND TBCOSTO.PESO_ACUMULADO <= 0.95 THEN 'C'
	  WHEN TBCOSTO.PESO_ACUMULADO > 1 AND TBCOSTO.PESO_ACUMULADO = 0 THEN 'O'
	  ELSE 'D' END AS STOCK_PROFILER_VALUE,
	  (DATEADD(mm, DATEDIFF(mm,0,DATEADD(MONTH,-1,GETDATE())),0))  AS FECHA_CIERRE,
	  	 CASE WHEN NUM_CLIENTES > 0 AND NUM_CLIENTES <= 1 THEN '9'
		  WHEN NUM_CLIENTES >= 2 AND NUM_CLIENTES <= 4 THEN '2'
		  WHEN NUM_CLIENTES >= 5 THEN '1'
		  ELSE '9' END AS STOCK_PROFILER_VALUE_2
--INTO EBIZ_STOCK_PROFILER_VTAS_TALLER
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.PESO,
SUM (PESO) OVER (PARTITION BY TB1.marca order by TB1.marca, TB1.VTAS DESC) AS PESO_ACUMULADO
FROM (
SELECT TB1.marca, TB1.COD_MATERIAL,TB1.VTAS, TB2.VTAS AS COSTO_INTERNO_MARCA, 
CASE WHEN TB2.VTAS = NULL THEN 0
 WHEN TB2.VTAS = 0 THEN 0
ELSE (CAST(TB1.VTAS AS decimal(18,10)) / CAST(TB2.VTAS AS decimal(18,10)) ) END AS PESO 

FROM #TB_STOCK_PROFILER_CONSUMO_MATERIAL TB1


INNER JOIN #TB_STOCK_PROFILER_CONSUMO_MARCA TB2 ON TB1.marca = TB2.marca ) TB1 ) TBCOSTO

LEFT JOIN #TABLA_STOCK_PROFILER_VENTAS_CLIENTES_2 TB2 ON TBCOSTO.COD_MATERIAL = TB2.COD_MATERIAL


DROP TABLE #TB_STOCK_PROFILER_CONSUMO_1
DROP TABLE #TB_STOCK_PROFILER_CONSUMO_2
DROP TABLE #TB_STOCK_PROFILER_CONSUMO_3
DROP TABLE #TB_STOCK_PROFILER_CONSUMO_MATERIAL
DROP TABLE #TB_STOCK_PROFILER_CONSUMO_MARCA
DROP TABLE #TABLA_STOCK_PROFILER_VENTAS_CLIENTES_1
DROP TABLE #TABLA_STOCK_PROFILER_VENTAS_CLIENTES_2


--------------------- ROTACION FINANCIERA ALMACENADA -----------------------------


DECLARE @CURRENT_DAY DATETIME ;
SET @CURRENT_DAY = DATEADD(DAY, -5, GETDATE());

DELETE FROM EBIZ_DATA_ROTACION_FINANCIERA_12M WHERE MONTH(FECHA_CORTE) = MONTH(@CURRENT_DAY) AND YEAR(FECHA_CORTE) = YEAR(@CURRENT_DAY)

INSERT INTO EBIZ_DATA_ROTACION_FINANCIERA_12M
SELECT TBCOSTO.COD_MATERIAL,TBCOSTO.COSTO AS COSTO_TOTAL, STOCK_DOLARES AS STOCK_TOTAL,

(TBCOSTO.COSTO / (STOCK_DOLARES / 12)) AS ROTACION_FINANCIERA,DATEADD(MONTH, 0, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', @CURRENT_DAY), '19000101'))  AS FECHA_CORTE
FROM (

SELECT A.COD_MATERIAL, sum(COSTO_INTERNO) AS COSTO
FROM ebiz_ventas A
WHERE fecha_completa >= DATEADD(MONTH, -12, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', @CURRENT_DAY), '19000101'))  

AND fecha_completa < DATEADD(MONTH, 0, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', @CURRENT_DAY), '19000101')) 

GROUP BY A.COD_MATERIAL ) TBCOSTO 

INNER JOIN (

SELECT A.COD_MATERIAL, sum(ECS_BLOQUEADO + ECS_CALIDAD + ECS_TRASLADO + ECS_LIBRE_UTILICACION) AS STOCK_DOLARES
FROM EBIZ_STOCK_AL_CIERRE A
WHERE FECHA_CIERRE >= DATEADD(MONTH, -12, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', @CURRENT_DAY), '19000101'))  
AND FECHA_CIERRE < DATEADD(MONTH, 0, DATEADD(MONTH, DATEDIFF(MONTH, '19000101', @CURRENT_DAY), '19000101')) 
GROUP BY A.COD_MATERIAL 
HAVING  sum(ECS_BLOQUEADO + ECS_CALIDAD + ECS_TRASLADO + ECS_LIBRE_UTILICACION) > 0
) TBSTOCK ON TBCOSTO.COD_MATERIAL = TBSTOCK.COD_MATERIAL
ORDER BY TBCOSTO.COD_MATERIAL





GO


